### ISSUE TITLE
Have option to use private repos

### ISSUE THREAD

**Issue by logandonley** [rht-labs/openshift-jenkins-s2i-config#40]
Currently, the config needs to be in a public repo, but it would be nice to have the functionality to use private repos as well.

**Comment by sherl0cks** [comment]
@logandonley that is tied to https://github.com/rht-labs/labs-ci-cd/tree/master/templates/jenkins-s2i-build, not this repo. can let's open an issue over at `labs-ci-cd`. closing this.
